export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";

export const REGISTER_PRIMARY_PUBLICK_KEY = "REGISTER_PRIMARY_PUBLICK_KEY";

export const REGISTER_PRIMARY_PUBLICK_KEY_FAILED =
  "REGISTER_PRIMARY_PUBLICK_KEY_FAILED";
export const REGISTER_SECONDARY = "REGISTER_SECONDARY";

export const GET_QUESTION = "GET_QUESTION";
export const SAVE_QUESTION_ANSWER = "SAVE_QUESTION_ANSWER";
export const SAVE_FIRST_QUESTION_ANSWER = "SAVE_FIRST_QUESTION_ANSWER";
export const EDIT_QUESTION_ANSWER = "EDIT_QUESTION_ANSWER";
export const CLEAR_EDIT_QUESTION_ANSWER = "CLEAR_EDIT_QUESTION_ANSWER";
export const SAVE_SECOND_QUESTION_ANSWER = "SAVE_SECOND_QUESTION_ANSWER";
export const SAVE_THIRD_QUESTION_ANSWER = "SAVE_THIRD_QUESTION_ANSWER";
export const CLEAR_QUESTION = "CLEAR_QUESTION";
