import { StyleSheet } from "react-native";
import * as font from "../../utils/FontFamily.js";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { colors } from "../../utils/ColorsCode.js";
export default StyleSheet.create({
  white: {
    position: "absolute",
    width: wp("100%"),
    height: hp("50%"),
    left: 0,
    top: 0,
    backgroundColor: "#FFFFFF",
    borderBottomEndRadius: 30,
    borderBottomLeftRadius: 30,
  },
  btnContainer: {
    padding: 26,
  },
  topContainer: {
    height: hp(40),
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    paddingTop: 26,
  },
  right_arrow: {
    marginTop: 20,
    marginBottom: 20,
    width: wp("6%"),
    height: wp("6%"),
    alignSelf: "flex-start",
  },
  greenTick: {
    width: wp("11%"),
    height: wp("11%"),
  },
  text1: {
    fontFamily: font.fontFamily.montserratSemiBold,
    fontWeight: "700",
    fontSize: 28,
    lineHeight: 36,
    textAlign: "center",
    letterSpacing: -0.165,
    color: colors.WHITE,
    paddingTop: 11,
  },
  text2: {
    fontFamily: font.fontFamily.regular,
    fontWeight: "400",
    fontSize: 19,
    lineHeight: 28,
    textAlign: "center",
    letterSpacing: -0.165,
    color: colors.WHITE,
    paddingTop: 8,
  },
  text3: {
    fontFamily: font.fontFamily.montserratSemiBold,
    fontWeight: "700",
    fontSize: 26,
    lineHeight: 31,
    textAlign: "center",
    letterSpacing: -0.165,
    color: colors.SECONDARY,
  },
  text4: {
    fontFamily: font.fontFamily.regular,
    fontWeight: "300",
    fontSize: 18,
    lineHeight: 26,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 8,
    textAlign: "center",
    letterSpacing: -0.165,
    color: colors.SECONDARY,
  },
  openMail: {
    fontFamily: font.FONT_REGULAR,
    fontWeight: "700",
    fontSize: 18,
    lineHeight: 22,
    textAlign: "center",
    letterSpacing: -0.165,
    color: colors.SECONDARY,
  },
  icon: {
    width: 12,
    height: 12,
    resizeMode: "contain",
    marginLeft: 4,
  },
  questionMark: {
    width: 45,
    height: 45,
    marginTop: 26,
    marginBottom: 16,
    alignSelf: "center",
  },
  openContainer: {
    position: "absolute",
    justifyContent: "center",
    alignSelf: "center",
    bottom: hp(15),
    flexDirection: "row",
    alignItems: "center",
  },
});
