import { StyleSheet } from "react-native";

import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { colors } from "../../utils/ColorsCode.js";
import { fontFamily } from "../../utils/FontFamily.js";
export default StyleSheet.create({
  right_arrow: {
    marginTop: 70,
    width: wp("6%"),
    height: wp("6%"),
    marginLeft: 40,
  },
  text1: {
    fontFamily: fontFamily.montserratSemiBold,
    fontSize: 28,
    textAlign: "center",
    letterSpacing: -0.165,
    color: colors.SECONDARY,
    paddingTop: hp(12),
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  text2: {
    fontFamily: fontFamily.regular,
    fontWeight: "400",
    fontSize: 19,
    lineHeight: 28,
    textAlign: "center",
    letterSpacing: -0.165,
    color: colors.SECONDARY,
    paddingTop: 8,
  },
  input1: {
    padding: 15,
    borderWidth: 1,
    backgroundColor: "#FFFFFF",
    borderColor: colors.GREY,
    borderRadius: 6,
    marginLeft: 26,
    marginRight: 26,
    marginTop: 26,
    fontSize: 18,
    fontFamily: fontFamily.regular,
  },
  input1Focus: {
    padding: 15,
    borderWidth: 1,
    backgroundColor: "#FFFFFF",
    borderColor: colors.PRIMARY,
    borderRadius: 6,
    marginLeft: 26,
    marginRight: 26,
    marginTop: 26,
    fontSize: 18,
    fontFamily: fontFamily.regular,
  },
  input2: {
    padding: 15,
    borderWidth: 1,
    backgroundColor: "#FFFFFF",
    borderColor: colors.GREY,
    borderRadius: 6,
    marginLeft: 26,
    marginRight: 26,
    marginTop: 6,
    fontSize: 18,
    fontFamily: fontFamily.regular,
  },
  input2Focus: {
    padding: 15,
    borderWidth: 1,
    backgroundColor: "#FFFFFF",
    borderColor: colors.PRIMARY,
    borderRadius: 6,
    marginLeft: 26,
    marginRight: 26,
    marginTop: 6,
    fontSize: 18,
    fontFamily: fontFamily.regular,
  },
  btn: {
    alignSelf: "center",
    height: 60,
    width: 340,
    backgroundColor: colors.PRIMARY,
    borderRadius: 6,
    marginTop: 16,
  },
  btnText: {
    color: colors.SECONDARY,
  },
  termsAndConditions: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: hp(6),
    fontFamily: fontFamily.regular,
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 19,
    textAlign: "center",
    letterSpacing: -0.165,
  },
});
